### ISSUE TITLE
Feature Requirement - as part of config service

### ISSUE THREAD

**Issue by JasonLamv-t** [typical-organization/param-store-service#14]
I have started this repo and finished reading the document. But I think this repo can not fully satisfy my needs because I just want to load env variables from ssm every time the app start, and use it via configService.

**Comment by parikmaan** [comment]
@JasonLamv-t Please share more details. Please share some code snippets to understand the issue.

**Comment by JasonLamv-t** [comment]
Thank you for your reply, @parikmaan!

For example, this is the way 2 describes on the document:

```
@Module({
    imports: [
        ConfigModule.forRoot({
            isGlobal: true,
            load: [configServiceParamStoreConfiguration],
            envFilePath: `config/${process.env.NODE_ENV || 'development'}.env`,
            validate,
        }),
        ParamStoreModule.registerAsync({
            import: ConfigModule,
            useClass: ConfigService,
        }),
    ],
    controllers: [AppController],
    providers: [AppService],
})
export class AppModule {
    constructor(
        private paramStoreService: ParamStoreService,
    ) {
        console.log('name', paramStoreService.get('name'));
    }
}
```
So we can see that we need to inject the configService into the paramStoreModule. 

But what I want like this:

```
@Module({
    imports: [
        ParamStoreModule.register({
            awsRegion: 'us-east-1',
            awsParamSorePath: '/application/config',
        }),
        ConfigModule.forRoot({
            isGlobal: true,
            load: [configServiceParamStoreConfiguration],
            envFilePath: ParamStoreModuleGenEnvFilePath,
            validate,
        }),
    ],
    controllers: [AppController],
    providers: [AppService],
})
export class AppModule {
    constructor(
        private configService: ConfigService,
    ) {
        console.log('name', configService.get('name'));
    }
}
```
I don't know if it's possible.

**Comment by parikmaan** [comment]
It will be possible. I think a new module needs to be written where instead of getting values from config module, it will read from inline hardcoded values passed in register block. 

But if you hardcode the values in the register block, it will not be configurable for different environments like dev, production etc. 

Any reason for not using configService?

**Comment by JasonLamv-t** [comment]
@parikmaan our project flow is like that:

trigger the cicd action > in the action, load env variables from ssm, and generate a `test.env` or `prod.env` file > in the dockerfile, pack this env file in the image

so, if we want to change the env variables, we have to finish the whole cicd process to make it effect. So I am looking for a solution that we can load env variables from ssm when the application is started. if so, we only need to restart the application.

And use it via configService, this can make it more suitable for more project.

In our current solution, the ssm path is quite fixed in this kind of format: `project/test` or `project/prod`, the poject name can be hard code, and we can use the `NODE_ENV` as the suffix.

**Comment by parikmaan** [comment]
@JasonLamv-t 

> trigger the cicd action > in the action, load env variables from ssm, and generate a test.env or prod.env file > in the dockerfile, pack this env file in the image

Is this the target configuration you want?

> so, if we want to change the env variables, we have to finish the whole cicd process to make it effect. So I am looking for a solution that we can load env variables from ssm when the application is started. if so, we only need to restart the application.

Or this is the problem you are trying to solve?

If this is the problem you are trying to solve, you just need to have following in `.env` file for corresponding environment.

```
AWS_REGION='us-east-1'
AWS_PARAM_STORE_PATH='/application/config'
```

Then you can use the parameters in your application like:

```
constructor(
        private paramStoreService: ParamStoreService,
) {
    this.some_ssm_property = Number(
        this.paramStoreService.get(AppCommonConstant.SOME_SSM_PROPERTY_NAME),
    );
}
```

I am sorry I am not able to understand the issue we need to fix.

**Comment by JasonLamv-t** [comment]
@parikmaan Sorry, let me describe more details.

> trigger the cicd action > in the action, load env variables from ssm, and generate a test.env or prod.env file > in the dockerfile, pack this env file in the image 

This is our project's current solution for obtaining env variables from ssm, and using it in the project.
We are using GitHub Action for CICD, here are some code, FYI:

```
# part of ci-cd action yaml 
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    aws-access-key-id: ${{ secrets.AWS_KEY }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET }}
    aws-region: ${{ env.AWS_REGION }}

- name: Get env variables from AWS SSM
  uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.4.0
  with:
    ssm-path: /app-backend/test/
    get-children: true

- name: Generate env file
  run: |
    sh libs/config/generate-env.sh .test.env

- name: Build, tag, and push image to Amazon ECR
  id: build-image
  uses: docker/build-push-action@v6
  with:
    context: .
    file: ./Test.Dockerfile
    push: true
    provenance: false
    tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY}}:${{ github.sha }}, ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY}}:latest
    cache-from: type=gha
    cache-to: type=gha,mode=max
  env:
    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
```
As you can see, in the action part we load env variables from ssm and store these variables in a `.test.env` file by shell script.
Then, this `.test.env` file will be packed into the image and loaded by the nest config module, as the nestjs doc recommended.

This will bring an issue that, if we change the env variable on the ssm, if we want to make it affect, we need to trigger the whole CI&CD process. This is what I want to solve.
Then, to solve this problem, I have an idea: why don't we load env variables when the container starts, so we only need to restart the container to make the changed env variables affect.

Fortunately, I found this useful pack, but it's a little bit different from what we want is that this pack use this way to obtain a variable: `this.paramStoreService.get(AppCommonConstant.SOME_SSM_PROPERTY_NAME)`,
And my ideal way is that: use this pack, we can load env variables from ssm, and inject these variables into the config module, and use them like the past way, like `this.configService.get('env_name')`, not needing to change existing code.
